---
# defaults file for spotify
spotify_gpg_key_url: https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg
spotify_keyring_path: /etc/apt/keyrings/spotify-archive-keyring.gpg
spotify_repo_url: http://repository.spotify.com
spotify_repo_distribution: stable
spotify_repo_component: non-free
spotify_package_name: spotify-client
