---
# defaults file for zsh

# User to configure zsh for (from vars.yml)
zsh_user: "{{ username }}"
zsh_user_home: "{{ user_home }}"

# Path to zshrc source file in repository
zshrc_source_file: "{{ playbook_dir }}/roles/zsh/files/zshrc"

# Oh My Zsh configuration
ohmyzsh_install_url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
ohmyzsh_dir: "{{ zsh_user_home }}/.oh-my-zsh"

# Powerlevel10k theme
p10k_repo: https://github.com/romkatv/powerlevel10k.git
p10k_dir: "{{ ohmyzsh_dir }}/custom/themes/powerlevel10k"
p10k_version: master  # Can be pinned to a specific tag

# Additional configuration
zsh_set_as_default_shell: true
