---
# defaults file for helm

# Helm repository configuration
helm_gpg_key_url: https://baltocdn.com/helm/signing.asc
helm_gpg_keyring_path: /usr/share/keyrings/helm.gpg
helm_repo_url: https://baltocdn.com/helm/stable/debian/
helm_package_name: helm
helm_package_state: present

# User configuration
helm_user: "{{ username }}"
helm_user_home: "{{ user_home }}"
