---
# handlers file for zram

- name: Restart zram service
  ansible.builtin.systemd:
    name: zram
    state: restarted
    daemon_reload: true
  when:
    - zram_method == 'manual'
    - not ansible_check_mode
